hw-3 MVP
Monophobiia/crypto-frontend pull request #1
Opened 2022-08-28 19:58 UTC by Monophobiia

Added basic components, routing, data fetching from API, css-modules, infinite scrolling.

Plans:
1. Category filtration.
2. Graphs.

2022-08-31 21:26 UTC, pavellap requested changes
В целом по коду норм, будь чуть внимательнее со стилизацией и старайся переиспользовать логику, дробя её на отдельные функции + файл со стилями всегда оставляй рядом с компонентом, так легче читать стили

2022-08-31 21:26 UTC, pavellap commented on package.json
> +    "@testing-library/user-event": "^13.2.1",
На будущее: зависимости с декларацией типов `@types` и  зависимости для тестирования лучше выносить в `devDependencies`

2022-08-31 21:26 UTC, pavellap commented on src/components/App/App.tsx
> +import styles from "@styles/App.module.scss";
лучше придерживаться немного другой структуры файлов: Директория -> `[App.tsx, index.ts, App.module.scss`, то есть хранить сам файл со стилями в самой директории с компонентом

2022-08-31 21:26 UTC, pavellap commented on src/components/App/App.tsx
> +            path="/"
Все роуты выносим в единый конфиг, чтобы затем их удобно можно было переиспользовать

2022-08-31 21:26 UTC, pavellap commented on src/components/Button/Button.tsx
> +import classnames from "classnames";
на самом деле большинство в сообществе привыкли этот импорт более сокращённым делать - `import cn from 'classnames'`

2022-08-31 21:26 UTC, pavellap commented on src/components/Button/Button.tsx
> +import { Loader } from "../Loader/Loader";
Импорт можно сделать короче, если добавить index.ts, не забывай про индексовые файлы

2022-08-31 21:26 UTC, pavellap commented on src/components/App/App.tsx
> +          <Route path="/coin">
роуты рекомендую выносить в отдельные конфиги, так их легче менять + переиспользовать

2022-08-31 21:26 UTC, pavellap commented on src/components/Button/Button.tsx
> +        "button_color-" + color,
удобнее использовать шаблонные литералы, получится: `button-color-${color}`

2022-08-31 21:26 UTC, pavellap commented on src/components/Button/Button.tsx
> +      {children} {loading ? <Loader /> : ""}
лучше возвращать null вместо пустой строки, null === пустое значение

2022-08-31 21:26 UTC, pavellap commented on src/components/Card/Card.tsx
> +      <img src={image} className={styles.card__image}></img>
не забывай про самозакрывающиеся теги

2022-08-31 21:26 UTC, pavellap commented on src/components/Card/Card.tsx
> +export const Card: React.FC<CardProps> = ({
не уверен, что это компонент не с курсов, но я бы вместо компонентов принимал строчки, которые уже в нужном виде с нужными стилями рендерил бы

2022-08-31 21:26 UTC, pavellap commented on src/components/Card/Card.tsx
> +export const Card: React.FC<CardProps> = ({
не забывай про оптимизацию, `React.memo`

2022-08-31 21:26 UTC, pavellap commented on src/components/CheckBox/CheckBox.tsx
> +  const [isChecked, setChecked] = useState(checked);
такое чувство, что копипаста с чужой домашки, точно сам всё делал?
На самом деле нет необходимости в этом состоянии, оно полностью дублирует состояние, которое прокидывается пропсами в этот компонент извне

2022-08-31 21:26 UTC, pavellap commented on src/components/Coin/Coin.tsx
> +const Coin: React.FC = () => {
предлагаю придерживаться немного другой логики в структуре файлов: `src/pages/Coin`

2022-08-31 21:26 UTC, pavellap commented on src/components/Coin/Coin.tsx
> +import arrow_left from "../../assets/arrow_left.png";
не забывай использовать алиасы

2022-08-31 21:26 UTC, pavellap commented on src/components/Coin/Coin.tsx
> +      const result = await axios({
Смотри, в библиотеке `axios` есть возможность создавать экземпляр через `axios.create` и устанавливать для него адрес для api по умолчанию, изучи документацию для этого
Так же предлагаю сразу вынести всю логику с запросами в отдельную функцию или даже хук, в котором у нас будет состояния `isLoading` и `isError`

2022-08-31 21:26 UTC, pavellap commented on src/components/Coin/Coin.tsx
> +  const [coin, setCoin] = useState({});
лучше сделать так: `  const [coin, setCoin] = useState<Card | null>(null);`

2022-08-31 21:26 UTC, pavellap commented on src/components/Coin/Coin.tsx
> +
и соответственно: `if (!coin) { return null }`

2022-08-31 21:26 UTC, pavellap commented on src/components/Coin/Coin.tsx
> +import arrow_left from "../../assets/arrow_left.png";
нейминг не забывай правильно делать: arrowLeft, в javascript принят нейминг через `camelCase`

2022-08-31 21:26 UTC, pavellap commented on src/variables.scss
> +$main-background: #F5F5F5;
красиво, молодца, что вынес всё в отдельный конфиг!

2022-08-31 21:26 UTC, pavellap commented on src/styles/MultiDropdown.module.scss
> +    color: #6C757D;
цвет не забываем выносить в конфиг

2022-08-31 21:26 UTC, pavellap commented on src/styles/MultiDropdown.module.scss
> +        padding-bottom: 3%;
так точно не надо делать, паддинги задаём в абсолютных величинах + у тебя это свойство конфликтует со свойством выше

2022-08-31 21:26 UTC, pavellap commented on src/styles/Header.module.scss
> +.selected {
старайся группировать правила всё-таки, раз решил БЭМа придерживаться

2022-08-31 21:26 UTC, pavellap commented on src/styles/Header.module.scss
> +        width: 255%;
переделай вёрстку, очень странное решение

2022-08-31 21:26 UTC, pavellap commented on src/components/Coins/Coins.tsx
> +                id: raw.id,
вот такую конструкцию можно в отдельную функцию-нормализатор вынести

2022-08-31 21:26 UTC, pavellap commented on src/components/Coins/Coins.tsx
> +              (s) => (o) =>
старайся не использовать однобуквенные переменные, не совсем понятно что происходит + сложные к сложным вещам оставляй комменты

2022-08-31 21:26 UTC, pavellap commented on src/components/Coins/Coins.tsx
> +        onChange={(item) => {
onChange={setCurrency}

2022-08-31 21:26 UTC, pavellap commented on src/components/Coins/Coins.tsx
> +          <p style={{ textAlign: "center" }}>
старайся не использовать инлайн стили, выноси всё в классы

2022-08-31 21:26 UTC, pavellap commented on src/components/Coins/Coins.tsx
> +        {coins
старайся в самом jsx ничего не преобразовывать и не фильтровать, для этого есть тело функции

2022-08-31 21:26 UTC, pavellap commented on src/components/Coins/Coins.tsx
> +              (raw: {
вынести этот объект в отдельный тип, которые потом сможешь переиспользовать

2022-08-31 21:26 UTC, pavellap commented on src/components/WithLoader/WithLoader.tsx
> +      <div>{children}</div>
лишний див

2022-08-31 21:26 UTC, pavellap commented on src/components/MultiDropdown/MultiDropdown.tsx
> +    toggle = () => {
не забывай про оптимизацию, useCallback

2022-08-31 21:26 UTC, pavellap commented on src/components/MultiDropdown/MultiDropdown.tsx
> +        {/* Can use this to show arrow/button that opens a dropdown */}
оставь их, проще будет пользоваться дропдауном

2022-08-31 21:26 UTC, pavellap commented on src/components/Header/header.tsx
> +import { MultiDropdown, Option } from "@components/MultiDropdown/MultiDropdown";
не забываем про index.ts и сокращенные импорты

2022-08-31 21:26 UTC, pavellap commented on src/components/Header/header.tsx
> +            currentTab ? "" : styles.selected
currentTab && styles.selected, classnames сам всё отфильтрует

2022-08-31 21:26 UTC, pavellap commented on src/components/Header/header.tsx
> +          to="/loser"
а ссылки как раз из конфигов возьмёшь

2022-08-31 21:26 UTC, pavellap commented on src/components/Header/header.tsx
> +          currentTab ? "" : ""
???

2022-08-31 21:26 UTC, pavellap commented on src/components/Input/Input.tsx
> +    if (typeof onChange === "function") {
проверка бессмысленная, у тебя ts ограничивает значение и так

2022-08-31 21:26 UTC, pavellap commented on src/components/Input/Input.tsx
> +        { ...rest }.disabled ? "input_disabled" : "",
а вытащи заранее disabled в пропсах

2022-08-31 21:26 UTC, pavellap commented on src/components/Loader/Loader.tsx
> +    return <div className={classnames(className, "loader_size-" + size)}></div>;
if (!loading) return null

2022-08-31 21:26 UTC, pavellap commented on src/components/Loader/Loader.tsx
> +    return <div className={classnames(className, "loader_size-" + size)}></div>;
самозакрывающийся тег

2022-08-31 21:26 UTC, pavellap commented on src/styles/App.module.scss
> +        width: 25%;
лучше задай максимальную ширину для этого блока и растяни его, так адаптивить легче будет

2022-08-31 21:26 UTC, pavellap commented on src/styles/App.module.scss
> +        height: 95vh;
старайся высоту через проценты задавать

2022-08-31 21:26 UTC, pavellap commented on src/styles/Coin.module.scss
> +        font-size: small;
через пиксели

2022-08-31 21:26 UTC, pavellap commented on src/styles/Coin.module.scss
> +        padding-left: 1%;
аналогично: все отступы делаем через пиксели

2022-09-04 19:01 UTC, Monophobiia commented on src/components/CheckBox/CheckBox.tsx
> +  const [isChecked, setChecked] = useState(checked);
Да, сам

Изначально не до конца было понятно, что требуется сделать dumb компоненты, это было ещё во втором модуле. Потом поправили описание, а я просто забыл убрать лишнее отсюда, тесты-то уже прошли. Отсюда и схожесть, у других наверняка похожие ситуации

2022-09-12 20:00 UTC, merged